version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3010:3010"
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
  test:
    build: ./backend
    command: ["npm", "test"]
networks:
  app-network: