name: CI/CD Pipeline

on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Dar permisos de ejecución a Jest
        run: chmod +x node_modules/.bin/jest
        working-directory: backend

      - name: Verificar instalación de Jest
        run: npx jest --version
        working-directory: backend

      - name: Run backend tests
        run: npm test
        working-directory: backend