name: CI/CD Pipeline

on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Run backend tests
        run: npm test
        working-directory: backend

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Run frontend tests
        run: npm test
        working-directory: frontend